package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

public class main extends javax.swing.JFrame {

    public static String infoData = "";

    // icono del JFrame
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    }

    public main() {
        initComponents();

        // como queremos que un form se cargue por defecto ponemos lo siguiente:
        FormHome fh = new FormHome();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        
        // definimos nuevo icono
        setIconImage(getIconImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nav = new javax.swing.JPanel();
        ButtonHome = new javax.swing.JLabel();
        ButtonNodosDistancias = new javax.swing.JLabel();
        ButtonBProdundidad = new javax.swing.JLabel();
        ButtonEscaladaSimple = new javax.swing.JLabel();
        ButtonPrimeroMejor = new javax.swing.JLabel();
        PanelHeader = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TituloForm = new javax.swing.JLabel();
        PanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(900, 550));

        Nav.setBackground(new java.awt.Color(201, 214, 223));
        Nav.setPreferredSize(new java.awt.Dimension(160, 379));
        Nav.setLayout(new java.awt.GridLayout(7, 0));

        ButtonHome.setBackground(new java.awt.Color(201, 214, 223));
        ButtonHome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonHome.setText("Home");
        ButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonHome.setOpaque(true);
        ButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseReleased(evt);
            }
        });
        Nav.add(ButtonHome);

        ButtonNodosDistancias.setBackground(new java.awt.Color(201, 214, 223));
        ButtonNodosDistancias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ButtonNodosDistancias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonNodosDistancias.setText("<html><p style=\"text-align:center\">Seleccionar Datos</p></html>");
        ButtonNodosDistancias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNodosDistancias.setOpaque(true);
        ButtonNodosDistancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNodosDistanciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonNodosDistanciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonNodosDistanciasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonNodosDistanciasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonNodosDistanciasMouseReleased(evt);
            }
        });
        Nav.add(ButtonNodosDistancias);

        ButtonBProdundidad.setBackground(new java.awt.Color(201, 214, 223));
        ButtonBProdundidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ButtonBProdundidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonBProdundidad.setText("fase de grupos");
        ButtonBProdundidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBProdundidad.setOpaque(true);
        ButtonBProdundidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBProdundidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonBProdundidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonBProdundidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonBProdundidadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonBProdundidadMouseReleased(evt);
            }
        });
        Nav.add(ButtonBProdundidad);

        ButtonEscaladaSimple.setBackground(new java.awt.Color(201, 214, 223));
        ButtonEscaladaSimple.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ButtonEscaladaSimple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonEscaladaSimple.setText("finales");
        ButtonEscaladaSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEscaladaSimple.setOpaque(true);
        ButtonEscaladaSimple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEscaladaSimpleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEscaladaSimpleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEscaladaSimpleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonEscaladaSimpleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonEscaladaSimpleMouseReleased(evt);
            }
        });
        Nav.add(ButtonEscaladaSimple);

        ButtonPrimeroMejor.setBackground(new java.awt.Color(201, 214, 223));
        ButtonPrimeroMejor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ButtonPrimeroMejor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPrimeroMejor.setText("Datos equipos");
        ButtonPrimeroMejor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonPrimeroMejor.setOpaque(true);
        ButtonPrimeroMejor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPrimeroMejorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonPrimeroMejorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonPrimeroMejorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonPrimeroMejorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonPrimeroMejorMouseReleased(evt);
            }
        });
        Nav.add(ButtonPrimeroMejor);

        getContentPane().add(Nav, java.awt.BorderLayout.WEST);

        PanelHeader.setBackground(new java.awt.Color(82, 97, 107));
        PanelHeader.setPreferredSize(new java.awt.Dimension(743, 75));
        PanelHeader.setLayout(new java.awt.BorderLayout());

        PanelLogo.setBackground(new java.awt.Color(82, 97, 107));
        PanelLogo.setPreferredSize(new java.awt.Dimension(160, 75));
        PanelLogo.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoImagen.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel1.setPreferredSize(new java.awt.Dimension(55, 51));
        PanelLogo.add(jLabel1, java.awt.BorderLayout.CENTER);

        PanelHeader.add(PanelLogo, java.awt.BorderLayout.WEST);

        TituloForm.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TituloForm.setForeground(new java.awt.Color(255, 255, 255));
        TituloForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloForm.setText("Home");
        PanelHeader.add(TituloForm, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelHeader, java.awt.BorderLayout.NORTH);

        PanelContent.setBackground(new java.awt.Color(253, 253, 253));
        PanelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        PanelContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // codigo para cuando nuestro boton Home hace click 
    private void ButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseClicked
        // Mostramos el contenido de nuestro JPanel pertinente en nuestro Form
        FormHome fh = new FormHome();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        // cambiamos titulo del form main
        TituloForm.setText("Home");
    }//GEN-LAST:event_ButtonHomeMouseClicked

    // codigo para cuando nuestro boton De seleccionar Nodos y Distancias hace click 
    private void ButtonNodosDistanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNodosDistanciasMouseClicked
        // Mostramos el contenido de nuestro JPanel pertinente en nuestro Form
        FormSeleccionDatos fh = new FormSeleccionDatos();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        // cambiamos titulo del form main
        TituloForm.setText("Seleccion de Informaicon");
    }//GEN-LAST:event_ButtonNodosDistanciasMouseClicked

    // codigo para cuando nuestro boton De busqueda por profudidad hace click 
    private void ButtonBProdundidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBProdundidadMouseClicked
        // Mostramos el contenido de nuestro JPanel pertinente en nuestro Form
        FormFaseGrupos fh = new FormFaseGrupos();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        // cambiamos titulo del form main
        TituloForm.setText("Fase de Grupos");
    }//GEN-LAST:event_ButtonBProdundidadMouseClicked

    // codigo para cuando nuestro boton De busqueda por escalada simple hace click 
    private void ButtonEscaladaSimpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEscaladaSimpleMouseClicked
        // Mostramos el contenido de nuestro JPanel pertinente en nuestro Form
        
        FormFinales fh = new FormFinales();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        // cambiamos titulo del form main
        TituloForm.setText("Finales");
    }//GEN-LAST:event_ButtonEscaladaSimpleMouseClicked

    // codigo para cuando nuestro boton De busqueda primero mejor hace click 
    private void ButtonPrimeroMejorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrimeroMejorMouseClicked
        // Mostramos el contenido de nuestro JPanel pertinente en nuestro Form
        FormDatosTable fh = new FormDatosTable();
        fh.setSize(690, 325);
        fh.setLocation(0, 0);
        PanelContent.removeAll();
        PanelContent.add(fh, BorderLayout.CENTER);
        PanelContent.revalidate();
        PanelContent.repaint();
        // cambiamos titulo del form main
        TituloForm.setText("Informacion Equipo");
    }//GEN-LAST:event_ButtonPrimeroMejorMouseClicked

    // metodos de UI sin importancia realmente 
    private void ButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseEntered
        ButtonHome.setBackground(new Color(82, 97, 107));
        ButtonHome.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButtonHomeMouseEntered

    private void ButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseExited
        ButtonHome.setBackground(new Color(201, 214, 223));
        ButtonHome.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ButtonHomeMouseExited

    private void ButtonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMousePressed
        ButtonHome.setBackground(new Color(30, 32, 34));
    }//GEN-LAST:event_ButtonHomeMousePressed

    private void ButtonHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseReleased
        ButtonHome.setBackground(new Color(82, 97, 107));
    }//GEN-LAST:event_ButtonHomeMouseReleased

    private void ButtonNodosDistanciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNodosDistanciasMouseEntered
        ButtonNodosDistancias.setBackground(new Color(82, 97, 107));
        ButtonNodosDistancias.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButtonNodosDistanciasMouseEntered

    private void ButtonNodosDistanciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNodosDistanciasMouseExited
        ButtonNodosDistancias.setBackground(new Color(201, 214, 223));
        ButtonNodosDistancias.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ButtonNodosDistanciasMouseExited

    private void ButtonNodosDistanciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNodosDistanciasMousePressed
        ButtonNodosDistancias.setBackground(new Color(30, 32, 34));
    }//GEN-LAST:event_ButtonNodosDistanciasMousePressed

    private void ButtonNodosDistanciasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNodosDistanciasMouseReleased
        ButtonNodosDistancias.setBackground(new Color(82, 97, 107));
    }//GEN-LAST:event_ButtonNodosDistanciasMouseReleased

    private void ButtonBProdundidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBProdundidadMouseEntered
        ButtonBProdundidad.setBackground(new Color(82, 97, 107));
        ButtonBProdundidad.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButtonBProdundidadMouseEntered

    private void ButtonBProdundidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBProdundidadMouseExited
        ButtonBProdundidad.setBackground(new Color(201, 214, 223));
        ButtonBProdundidad.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ButtonBProdundidadMouseExited

    private void ButtonBProdundidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBProdundidadMousePressed
        ButtonBProdundidad.setBackground(new Color(30, 32, 34));
    }//GEN-LAST:event_ButtonBProdundidadMousePressed

    private void ButtonBProdundidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBProdundidadMouseReleased
        ButtonBProdundidad.setBackground(new Color(82, 97, 107));
    }//GEN-LAST:event_ButtonBProdundidadMouseReleased

    private void ButtonEscaladaSimpleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEscaladaSimpleMouseEntered
        ButtonEscaladaSimple.setBackground(new Color(82, 97, 107));
        ButtonEscaladaSimple.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButtonEscaladaSimpleMouseEntered

    private void ButtonEscaladaSimpleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEscaladaSimpleMouseExited
        ButtonEscaladaSimple.setBackground(new Color(201, 214, 223));
        ButtonEscaladaSimple.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ButtonEscaladaSimpleMouseExited

    private void ButtonEscaladaSimpleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEscaladaSimpleMousePressed
        ButtonEscaladaSimple.setBackground(new Color(30, 32, 34));
    }//GEN-LAST:event_ButtonEscaladaSimpleMousePressed

    private void ButtonEscaladaSimpleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEscaladaSimpleMouseReleased
        ButtonEscaladaSimple.setBackground(new Color(82, 97, 107));
    }//GEN-LAST:event_ButtonEscaladaSimpleMouseReleased

    private void ButtonPrimeroMejorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrimeroMejorMouseEntered
        ButtonPrimeroMejor.setBackground(new Color(82, 97, 107));
        ButtonPrimeroMejor.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButtonPrimeroMejorMouseEntered

    private void ButtonPrimeroMejorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrimeroMejorMouseExited
        ButtonPrimeroMejor.setBackground(new Color(201, 214, 223));
        ButtonPrimeroMejor.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ButtonPrimeroMejorMouseExited

    private void ButtonPrimeroMejorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrimeroMejorMousePressed
        ButtonPrimeroMejor.setBackground(new Color(30, 32, 34));
    }//GEN-LAST:event_ButtonPrimeroMejorMousePressed

    private void ButtonPrimeroMejorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrimeroMejorMouseReleased
        ButtonPrimeroMejor.setBackground(new Color(82, 97, 107));
    }//GEN-LAST:event_ButtonPrimeroMejorMouseReleased

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonBProdundidad;
    private javax.swing.JLabel ButtonEscaladaSimple;
    private javax.swing.JLabel ButtonHome;
    private javax.swing.JLabel ButtonNodosDistancias;
    private javax.swing.JLabel ButtonPrimeroMejor;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JLabel TituloForm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
